# segfaults sometimes

FROM alpine:3.5

RUN apk --no-cache add --virtual .build-deps \
    linux-headers build-base cmake curl \
  && cd /tmp \
  && curl -L https://github.com/fluent/fluent-bit/archive/v0.11.2.tar.gz \
    | tar -xz --strip 1 \
  && cmake -DFLB_DEBUG=On -DFLB_TRACE=On -DFLB_JEMALLOC=On -DFLB_BUFFERING=On . \
  && make \
  && make install \
  && rm -r /tmp/* \
  && apk del .build-deps

COPY ./conf /etc/fluent

# USER nobody:nobody
CMD ["fluent-bit", "--config=/etc/fluent/fluent-bit.conf"]
